# General
site_name: Shippable Docs
repo_url: https://github.com/Shippable/docsv2

# Paths
docs_dir: sources
theme_dir: theme/shippable

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']

# Pages
pages:
- Overview:
  - What is Shippable?: index.md
  - FAQ: faq.md
- Continuous Integration (CI):
  - Overview: ci/overview.md
  - What is supported?: ci/supported.md
  - Running a build: ci/runFirstBuild.md
  - Build configuration: ci/shippableyml.md
  - Languages:
    - Node.js: ci/languages/node.md
    - Python: ci/languages/python.md
    - Java: ci/languages/java.md
    - Clojure: ci/languages/clojure.md
    - Ruby: ci/languages/ruby.md
    - Go: ci/languages/go.md
    - PHP: ci/languages/php.md
    - Scala: ci/languages/scala.md
    - C: ci/languages/objc.md
    - Custom Images: ci/languages/customImages.md
  - Services:
    - CouchDB: ci/services/couchDB.md
    - Elastic Search: ci/services/elasticSearch.md
    - Memcached: ci/services/memcached.md
    - MongoDB: ci/services/mongoDB.md
    - MySQL: ci/services/mySQL.md
    - Neo4j: ci/services/neo4j.md
    - Postgres: ci/services/postgreSQL.md
    - RabbitMQ: ci/services/rabbitMQ.md
    - Redis: ci/services/redis.md
    - RethinkDB: ci/services/rethinkDB.md
    - Riak: ci/services/riak.md
    - Selenium: ci/services/selenium.md
    - SQLite: ci/services/sqlite.md
  - Advanced Options:
    - Environment Variables: ci/advancedOptions/environmentVariables.md
    - Including/Excluding branches: ci/advancedOptions/branches.md
    - Matrix builds: ci/advancedOptions/matrixBuilds.md
    - Caching: ci/advancedOptions/caching.md
    - Artifacts: ci/advancedOptions/artifacts.md
    - Using git submodules: ci/advancedOptions/gitSubmodules.md
    - Shippable_retry: ci/advancedOptions/retry.md
    - Skipping builds: ci/advancedOptions/skipBuild.md
    - Running builds on your own machines (BYON): ci/advancedOptions/byon.md
    - Test and Coverage Reports: ci/advancedOptions/testCoverage.md
    - Timeouts: ci/advancedOptions/timeouts.md
    - Node Machine Images: ci/advancedOptions/machineImages.md
  - Permissions: ci/permissions.md
  - Troubleshooting CI: ci/troubleshoot.md
- Continuous Deployment Pipelines:
  - Overview: pipelines/overview.md
  - Getting Started: pipelines/gettingStarted.md
  - Resources:
    - Overview: pipelines/resources/overview.md
    - cluster: pipelines/resources/cluster.md
    - dockerOptions: pipelines/resources/dockerOptions.md
    - file: pipelines/resources/file.md
    - gitRepo: pipelines/resources/gitRepo.md
    - image: pipelines/resources/image.md
    - integration: pipelines/resources/integration.md
    - loadBalancer: pipelines/resources/loadBalancer.md
    - notification: pipelines/resources/notification.md
    - params: pipelines/resources/params.md
    - replicas: pipelines/resources/replicas.md
    - time: pipelines/resources/time.md
    - version: pipelines/resources/version.md
  - Jobs:
    - Overview: pipelines/jobs/overview.md
    - manifest: pipelines/jobs/manifest.md
    - deploy: pipelines/jobs/deploy.md
    - release: pipelines/jobs/release.md
    - runSh: pipelines/jobs/runSh.md
    - jenkinsJob: pipelines/jobs/jenkinsJob.md
  - Triggers: pipelines/triggers.md
  - Trace: pipelines/trace.md
- Integrations:
  - Overview: integrations/overview.md
  - Source Control Systems:
    - Overview: integrations/scm/scmOverview.md
    - GitHub: integrations/scm/github.md
    - GitHub Enterprise: integrations/scm/githubEnterprise.md
    - Bitbucket: integrations/scm/bitbucket.md
    - Bitbucket Server: integrations/scm/bitbucketServer.md
    - GitLab: integrations/scm/gitlab.md
  - Notifications:
    - Slack: integrations/notifications/slack.md
    - Email: integrations/notifications/email.md
    - HipChat: integrations/notifications/hipchat.md
    - IRC: integrations/notifications/irc.md
    - Webhooks: integrations/notifications/webhooks.md
  - Image Registries:
    - Docker Hub: integrations/imageRegistries/dockerHub.md
    - Docker Trusted Registry: integrations/imageRegistries/dockerTrustedRegistry.md
    - Amazon EC2 Container Registry (ECR): integrations/imageRegistries/ecr.md
    - Google Container Registry (GCR): integrations/imageRegistries/gcr.md
    - Quay.io: integrations/imageRegistries/quay.md
    - Any Private Registry: integrations/imageRegistries/privateRegistry.md
  - Artifact Registries:
    - Jfrog Artifactory: integrations/artifactRegistries/jfrogArtifactory.md
  - Container Services:
    - Amazon EC2 Container Service (ECS): integrations/containerServices/ecs.md
    - Google Container Engine (GKE): integrations/containerServices/gke.md
    - Docker Cloud: integrations/containerServices/dockerCloud.md
    - Docker Datacenter: integrations/containerServices/dockerDatacenter.md
  - Deploy:
    - AWS Elastic Beanstalk: integrations/deploy/eb.md
    - Node Cluster: integrations/deploy/nodeCluster.md
  - Keys:
    - SSH: integrations/keys/ssh.md
    - PEM:  integrations/keys/pem.md
- Navigating the UI:
  - Home: navigatingUI/home.md
  - Account:
    - Account: navigatingUI/accountSettings/accounts.md
    - Integrations: navigatingUI/accountSettings/integrations.md
    - Cards: navigatingUI/accountSettings/cards.md
    - API: navigatingUI/accountSettings/api.md
  - Subscription:
    - CI: navigatingUI/subscriptions/ci.md
    - Pipelines: navigatingUI/subscriptions/pipelines.md
    - Settings: navigatingUI/subscriptions/settings.md
  - Project:
    - Status: navigatingUI/projects/status.md
    - Settings: navigatingUI/projects/settings.md
  - Build:
    - Overview: navigatingUI/builds/overview.md
    - Detail: navigatingUI/builds/detail.md
- API:
  - Overview: api/overview.md
  - Account routes: api/account.md
  - Subscription routes: api/subscription.md
  - Project routes: api/project.md
  - Job routes: api/job.md
  - Run routes: api/run.md
  - Status Code Mapping: api/statusMapping.md
- Shippable Server:
  - Overview: server/overview.md
  - Installing Shippable Server: server/installingShippableServer.md
  - Backup and Restore Procedures: server/backup-restore-procedures.md
- Tutorials:
  - CI Tutorials:
    - Run a sample CI build: tutorials/ci/runSampleCIBuild.md
    - Source Control Systems Tutorials:
      - Linking GitHub and Bitbucket accounts on Shippable: tutorials/ci/integrations/scm/linkGitHubAndBitbucket.md
      - Building Bitbucket Server repos: tutorials/ci/integrations/scm/usingBitbucketServer.md
      - Building GitLab repos: tutorials/ci/integrations/scm/usingGitLab.md
    - Docker registry tutorials:
      - Amazon ECR tutorials:
        - Pull Docker image from ECR: tutorials/ci/integrations/imageRegistries/amazon-ecr/pull-docker-image-from-aws-ecr.md
        - Build docker image: tutorials/ci/integrations/imageRegistries/amazon-ecr/build-docker-image.md
        - Push a Docker image to ECR: tutorials/ci/integrations/imageRegistries/amazon-ecr/push-docker-image-to-aws-ecr.md
        - Use custom Docker image from ECR for CI: tutorials/ci/integrations/imageRegistries/amazon-ecr/use-custom-ecr-docker-image-for-ci.md
      - Interacting with Docker Hub: tutorials/ci/integrations/imageRegistries/usingDockerHub.md
      - Interacting with Google Container Registry: tutorials/ci/integrations/imageRegistries/usingGCR.md
    - Test and Code Coverage Tutorials:
      - Advanced Coverage Reports with JaCoCo: tutorials/ci/integrations/codeCoverage/usingJacoco.md
    - Container Services Tutorials:
      - Using Docker Datacenter: tutorials/ci/integrations/containerServices/usingDockerDatacenter.md
    - Deploy Tutorials:
      - Using Heroku: tutorials/ci/integrations/deploy/usingHeroku.md
      - Using OpsWorks: tutorials/ci/integrations/deploy/usingOpsWorks.md
      - Using Code Deploy: tutorials/ci/integrations/deploy/usingCodeDeploy.md
      - Using Digital Ocean: tutorials/ci/integrations/deploy/usingDigitalOcean.md
  - Pipelines Tutorials:
    - Deploying a sample application: tutorials/pipelines/samplePipeline.md
    - Seeding your first pipeline: tutorials/pipelines/howToAddSyncRepos.md
    - Connecting CI and Pipelines: tutorials/pipelines/connectingCiPipelines.md
    - Rolling back deployments: tutorials/pipelines/rollback-deployments.md
    - runSh tutorials:
      - Using integrations with runSh: tutorials/pipelines/runShUseIntegrations.md
      - Updating resource version: tutorials/pipelines/updateResourceVersion.md
      - Extracting resource version information: tutorials/pipelines/extractVersionInformation.md
      - Persisting state between runs: tutorials/pipelines/persistStateBetweenRuns.md
- Search: search.md
